/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms;

import com.hms.jdbc.InsertUpdateDelete;
import com.hms.jdbc.Select;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anand
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    int id;
    String room;
    String bed;
    String roomType;
    public CustomerCheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jsearchText = new javax.swing.JTextField();
        jsearchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jnameText = new javax.swing.JTextField();
        jcheckinText = new javax.swing.JTextField();
        jcheckoutText = new javax.swing.JTextField();
        jmobileText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jpriceText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jdaysText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jamountText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jemailText = new javax.swing.JTextField();
        jcheckoutButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customerCheckOut.png"))); // NOI18N
        jLabel1.setText("Customer Check-Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 35, 241, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Room Number Or  Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 106, 173, -1));

        jsearchText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jsearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 103, 251, -1));

        jsearchButton.setBackground(new java.awt.Color(102, 0, 0));
        jsearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jsearchButton.setForeground(new java.awt.Color(255, 255, 255));
        jsearchButton.setText("Search");
        jsearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jsearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 103, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 189, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Check-IN Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 189, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Check-OUT Date ( Today )");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 189, 251, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1048, 189, 250, -1));

        jnameText.setEditable(false);
        jnameText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 227, 250, -1));

        jcheckinText.setEditable(false);
        jcheckinText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jcheckinText, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 227, 250, -1));

        jcheckoutText.setEditable(false);
        jcheckoutText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jcheckoutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 227, 251, -1));

        jmobileText.setEditable(false);
        jmobileText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jmobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1048, 227, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Per Day Room Cost");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 288, 250, -1));

        jpriceText.setEditable(false);
        jpriceText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jpriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 326, 250, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Number of Days Stayed");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 288, 250, -1));

        jdaysText.setEditable(false);
        jdaysText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jdaysText, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 326, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount to be Collected");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 288, 251, -1));

        jamountText.setEditable(false);
        jamountText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jamountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 326, 251, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1048, 288, 250, -1));

        jemailText.setEditable(false);
        jemailText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jemailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1048, 326, 250, -1));

        jcheckoutButton.setBackground(new java.awt.Color(102, 0, 0));
        jcheckoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcheckoutButton.setForeground(new java.awt.Color(255, 255, 255));
        jcheckoutButton.setText("Check Out");
        jcheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jcheckoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 379, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 379, 110, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 0, 40, 44));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Nationality", "Gender", "Email", "ID-Proof", "Address", "Check-IN Date", "Room Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 467, 1245, 212));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allPagesBackground.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(null,"Do you want to close Customer Check-OUT Section ?","Select proper option",JOptionPane.YES_NO_OPTION);
        if(option==0)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs=Select.executeSelectQuery("Select * from customers where checkoutdate is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString("room")});
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int option=JOptionPane.showConfirmDialog(null,"Do you want to clear all details ?","Select proper option",JOptionPane.YES_NO_OPTION);
        if(option==0)
        {
            setVisible(false);
            new CustomerCheckOut().setVisible(true);
        }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckoutButtonActionPerformed
        // TODO add your handling code here:
        String name=jnameText.getText();
        if(name.equals(""))
        {
           JOptionPane.showMessageDialog(null,"Kindly search for the Customer first !! No Customer Selected !!");
        }else
        {
            System.out.println("Check out started for "+name);
            String email=jemailText.getText();
            String checkindate=jcheckinText.getText();
            String checkoutdate=jcheckoutText.getText();
            String mobile=jmobileText.getText();
            String perdaycost=jpriceText.getText();
            String noofdaysstayed=jdaysText.getText();
            String amount=jamountText.getText();
            String query=String.format("update customers set checkoutdate='%s',days='%d',totalamount=%d where id=%d",checkoutdate,Integer.parseInt(noofdaysstayed),Integer.parseInt(amount),id);
            InsertUpdateDelete.executeCustomQuery(query,"");
            query=String.format("update rooms set status='Not Booked' where roomnumber=(Select room from customers where id=%d)",id);
            InsertUpdateDelete.executeCustomQuery(query,"");
            
            // generation PDF now
            System.out.println("Billing started for "+name);
            String path="D:\\HMS\\";
            com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
            try
            {
                PdfWriter.getInstance(doc,new FileOutputStream(path+""+id+".pdf"));
                doc.open();
                Paragraph p=new Paragraph("ANSHU HOTEL MANAGEMENT SYSTEM\n");
                doc.add(p);
                p=new Paragraph("**********************************************************\n");
                doc.add(p);
                p=new Paragraph("Customer Details : \n");
                doc.add(p);
                p=new Paragraph("\tName: "+name+"\n"+"\tMobile Number: "+mobile+"\n"+"\tEmail: "+email);
                doc.add(p);
                p=new Paragraph("**********************************************************\n");
                doc.add(p);
                p=new Paragraph("Room Details : \n");
                doc.add(p);
                p=new Paragraph("\tRoom Number: "+room+"\n"+"\tRoom Type: "+roomType+"\n"+"\tBed: "+bed+"\n\tPrice Per Day: Rs."+perdaycost);
                doc.add(p);
                p=new Paragraph("**********************************************************\n");
                doc.add(p);
                p=new Paragraph("Bill Details : \n");
                doc.add(p);
                p=new Paragraph("\tBill ID: "+id+"\n");
                doc.add(p);
                p=new Paragraph("\tCheck-IN Date: "+checkindate+"\n\tCheck-OUT Date: "+checkoutdate+"\n\tNo. of Days Stayed: "+noofdaysstayed+"\n\tTotal Amount: "+amount);
                doc.add(p);
                p=new Paragraph("**********************************************************\n");
                doc.add(p);
                p=new Paragraph("Thank You. Please Visit Again !!\n");
                doc.add(p);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
            doc.close();
            
            //opening of pdf(bill)
            int option=JOptionPane.showConfirmDialog(null,"Do you want to Open the Bill ?","Select proper option",JOptionPane.YES_NO_OPTION);
            if(option==0)
            {
                try
                {
                    if(new File(path+id+".pdf").exists())
                    {
                        Process p=Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+path+id+".pdf");
                    }else
                    {
                        JOptionPane.showMessageDialog(null,"File Doesnot exists!!");
                    }
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
            setVisible(false);
            new CustomerCheckOut().setVisible(true);
            System.out.println("Billing completed for "+name);
            System.out.println("Check out completed for "+name);
        }   
    }//GEN-LAST:event_jcheckoutButtonActionPerformed

    private void jsearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchButtonActionPerformed
        // TODO add your handling code here:
        String param=jsearchText.getText();
        System.out.println("Search in checkout form started for "+param);
        try
        {
            String query=String.format("select * from customers where email='%s' OR room='%s' AND checkoutdate IS NULL",param,param);
            ResultSet rs=Select.executeSelectQuery(query);
            if(rs.next())
            {
                id=rs.getInt("id");
                jnameText.setText(rs.getString("name"));
                jcheckinText.setText(rs.getString("checkindate"));
                jmobileText.setText(rs.getString("mobilenumber"));
                int priceperday=0;
                //System.out.println("Select * from rooms where roomnumber="+rs.getString("room"));
                ResultSet rs1=Select.executeSelectQuery("Select * from rooms where roomnumber="+rs.getString("room"));
                if(rs1.next())
                {
                 priceperday=rs1.getInt("price");
                 room=rs.getString("room");
                 bed=rs1.getString("bed");
                 roomType=rs1.getString("roomtype");
                 jpriceText.setText(Integer.toString(priceperday));
                }
                jemailText.setText(rs.getString("email"));
                //converting checkoutdate(by default todays date) to string
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                Calendar cal=Calendar.getInstance();
                jcheckoutText.setText(sdf.format(cal.getTime()));
                //java.sql.Date 
                
                //convert checkindate(String form) from text field to Date
                String checkindate=rs.getString("checkindate");
                java.util.Date checkin=sdf.parse(checkindate);
                
                String checkoutdate=sdf.format(cal.getTime());
                java.util.Date checkout=sdf.parse(checkoutdate);
                long diff=checkout.getTime()-checkin.getTime();
                int noofdaysstayed=(int)(diff/(1000*60*60*24));
                if(noofdaysstayed==0)
                    noofdaysstayed=1;
                jdaysText.setText(Integer.toString(noofdaysstayed));
                jamountText.setText(Integer.toString(noofdaysstayed*priceperday));
                System.out.println("Search in checkout form completed for "+param);
            }
            else
            {
                System.out.println("Search results not found for "+param); 
                JOptionPane.showMessageDialog(null,"No records found with specified value !!");
            } 
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jsearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jamountText;
    private javax.swing.JTextField jcheckinText;
    private javax.swing.JButton jcheckoutButton;
    private javax.swing.JTextField jcheckoutText;
    private javax.swing.JTextField jdaysText;
    private javax.swing.JTextField jemailText;
    private javax.swing.JTextField jmobileText;
    private javax.swing.JTextField jnameText;
    private javax.swing.JTextField jpriceText;
    private javax.swing.JButton jsearchButton;
    private javax.swing.JTextField jsearchText;
    // End of variables declaration//GEN-END:variables
}
