/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms;
import javax.swing.JOptionPane;
import com.hms.jdbc.Select;
import com.hms.jdbc.InsertUpdateDelete;
import java.sql.*;

/**
 *
 * @author Anand
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jsecurityquestion = new javax.swing.JTextField();
        janswer = new javax.swing.JTextField();
        jnewpassword = new javax.swing.JPasswordField();
        jsearch = new javax.swing.JButton();
        jsubmit = new javax.swing.JButton();
        jsignup = new javax.swing.JButton();
        jlogin = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot Password ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 217, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 105, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Security Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 105, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Answer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 105, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 105, -1));

        jemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 291, -1));

        jsecurityquestion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jsecurityquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 291, -1));

        janswer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(janswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 291, -1));

        jnewpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jnewpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 291, -1));

        jsearch.setBackground(new java.awt.Color(102, 0, 0));
        jsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jsearch.setForeground(new java.awt.Color(255, 255, 255));
        jsearch.setText("Search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });
        getContentPane().add(jsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, -1, -1));

        jsubmit.setBackground(new java.awt.Color(102, 0, 0));
        jsubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jsubmit.setForeground(new java.awt.Color(255, 255, 255));
        jsubmit.setText("Submit");
        jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jsignup.setBackground(new java.awt.Color(102, 0, 0));
        jsignup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jsignup.setForeground(new java.awt.Color(255, 255, 255));
        jsignup.setText("SignUp");
        jsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsignupActionPerformed(evt);
            }
        });
        getContentPane().add(jsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jlogin.setBackground(new java.awt.Color(102, 0, 0));
        jlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlogin.setForeground(new java.awt.Color(255, 255, 255));
        jlogin.setText("Login");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        getContentPane().add(jlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 47, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgotPassword.PNG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            int option=JOptionPane.showConfirmDialog(null,"Do you want to close the Application ?","Select proper option",JOptionPane.YES_NO_OPTION);
            if(option==0)
                System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
        // TODO add your handling code here:
        String email=jemail.getText();
        if(email.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Email field is empty !! Kindly enter your email id.!!");
        }else{
            String query=String.format("select * from hmsadmin where email='%s'",email);
            ResultSet rs=Select.executeSelectQuery(query);
            try
            {
                if(rs.next())
                {
                    System.out.println("User exist in hmsadmin :"+email);
                    jsecurityquestion.setEditable(false);
                    jemail.setEditable(false);
                    jsecurityquestion.setText(rs.getString("securityquestion"));
                }else{
                    System.out.println("User doesnot exist in hmsadmin:"+email);
                }
            }
            catch(Exception e)
            {
                  System.out.println("Exception occurred in Searching email\n"+e);
                  JOptionPane.showMessageDialog(null,e);
            }
        }
        
    }//GEN-LAST:event_jsearchActionPerformed

    private void jsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmitActionPerformed
        // TODO add your handling code here:
        String email=jemail.getText();
        String securityquestion=jsecurityquestion.getText();
        String answer=janswer.getText();
        String newpassword=jnewpassword.getText();
        if(email.equals("") || securityquestion.equals("") || answer.equals("") || newpassword.equals(""))
        {
            JOptionPane.showMessageDialog(null,"All fields are required !!");
        }else{
            //check whether enter securityanswer is same as in database, if same then change the password;
            String query=String.format("Select securityanswer from hmsadmin where email='%s'",email);
            ResultSet rs=Select.executeSelectQuery(query);
            try{
                if(rs.next())
                {
                    if(rs.getString("securityanswer").equals(answer))
                    {
                        System.out.println("Answer matched with database");
                        query=String.format("update hmsadmin set password='%s' where email='%s'",newpassword,email);
                        InsertUpdateDelete.executeCustomQuery(query,"Password Change is successful.");
                        setVisible(false);
                        new ForgotPassword().setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null,"Sorry incorrect answer for security question !! Kindly enter the correct answer to reset the password");
                    }
                }
            }
            catch(Exception e){
                System.out.println("Exception occurred while changing password :"+e);
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_jsubmitActionPerformed

    private void jsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsignupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SignUp().setVisible(true);
    }//GEN-LAST:event_jsignupActionPerformed

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField janswer;
    private javax.swing.JTextField jemail;
    private javax.swing.JButton jlogin;
    private javax.swing.JPasswordField jnewpassword;
    private javax.swing.JButton jsearch;
    private javax.swing.JTextField jsecurityquestion;
    private javax.swing.JButton jsignup;
    private javax.swing.JButton jsubmit;
    // End of variables declaration//GEN-END:variables
}
