/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms;

import com.hms.jdbc.InsertUpdateDelete;
import com.hms.jdbc.Select;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anand
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jroomNumber = new javax.swing.JLabel();
        jroomNumberText = new javax.swing.JTextField();
        jroomType = new javax.swing.JLabel();
        jroomTypeText = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbedText = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jpriceText = new javax.swing.JTextField();
        jaddRoom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manageRoom.png"))); // NOI18N
        jLabel1.setText("Manage Room");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        getContentPane().add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1324, 6, 36, 34));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 760, 438));

        jroomNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jroomNumber.setText("Room Number");
        getContentPane().add(jroomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 127, 440, -1));

        jroomNumberText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jroomNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jroomNumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(jroomNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 165, 440, -1));

        jroomType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jroomType.setText("Room Type");
        getContentPane().add(jroomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 209, 440, -1));

        jroomTypeText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jroomTypeText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        getContentPane().add(jroomTypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 247, 440, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Bed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 291, 440, -1));

        jbedText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbedText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        getContentPane().add(jbedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 329, 440, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 373, 440, -1));

        jpriceText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jpriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 411, 440, -1));

        jaddRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jaddRoom.setForeground(new java.awt.Color(102, 0, 0));
        jaddRoom.setText("Add Room");
        jaddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddRoomActionPerformed(evt);
            }
        });
        getContentPane().add(jaddRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 455, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/allPagesBackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jroomNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jroomNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jroomNumberTextActionPerformed

    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed
        int option=JOptionPane.showConfirmDialog(null,"Do you want to close the Manage Room Section ?","Select proper option",JOptionPane.YES_NO_OPTION);
        if(option==0)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_jexitActionPerformed

    private void jaddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddRoomActionPerformed
        // TODO add your handling code here:
        try
        {
            
            String roomNumber=jroomNumberText.getText().strip();
            String roomType=((String)jroomTypeText.getSelectedItem()).strip();
            String bed=((String)jbedText.getSelectedItem()).strip();
            String price=jpriceText.getText();
            
            if(roomNumber.equals("")||roomType.equals("")|| bed.equals("")|| price.equals(""))
            {
                
                JOptionPane.showMessageDialog(null,"Please Enter All Details !!");
            }else{
                String query=String.format("insert into rooms(roomnumber,roomtype,bed,price) values('%s','%s','%s',%d)",roomNumber,roomType,bed,Integer.parseInt(price));
                InsertUpdateDelete.executeCustomQuery(query,"Room Added Successfully"); 
                setVisible(false);
                new ManageRoom().setVisible(true);
            }
        }catch(Exception e){
            System.out.println("Exception occured in adding room\n"+e);
        }
    }//GEN-LAST:event_jaddRoomActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        try{
            ResultSet rs=Select.executeSelectQuery("Select * from rooms");
            if(rs!=null)
            {
                while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getString(5)});
                }
            }
            rs.close();
        }catch(Exception e){
            System.out.println("Exception occured in viewing all rooms in ManageRooms\n"+e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jaddRoom;
    private javax.swing.JComboBox<String> jbedText;
    private javax.swing.JButton jexit;
    private javax.swing.JTextField jpriceText;
    private javax.swing.JLabel jroomNumber;
    private javax.swing.JTextField jroomNumberText;
    private javax.swing.JLabel jroomType;
    private javax.swing.JComboBox<String> jroomTypeText;
    // End of variables declaration//GEN-END:variables
}
